### PR TITLE
Bug 1809647: Align with latest changes upstream

### PR DESCRIPTION
**Pull request by elfosardo**
Convert to dnf
Completely remove mdns configuration
Remove sqlite after usage
Remove iptables filters

Related changes in metal3-io
https://github.com/metal3-io/ironic-inspector-image/pull/37
https://github.com/metal3-io/ironic-inspector-image/pull/39
https://github.com/metal3-io/ironic-inspector-image/pull/41
https://github.com/metal3-io/ironic-inspector-image/pull/44

### CODE REVIEW

**Comment by stbenjam** [comment]
Remove the hold when you're ready for it to be merged, but looks like there's still discussion on the 4.5/master branch PR about cherry-picking.

**Comment by elfosardo** [comment]
@stbenjam  thanks, #28 was merged as-is, so I'm going to unhold this one too

**Pull request merged**
