### PR TITLE
Bug 2023765: For inspector, compare IPs using the short form of IPv6 address

### PR DESCRIPTION
**Pull request by bfournie**
In 4.8, the change to use ipcalc to convert a long-form IPv6 address to a short-form address (which is returned by the ip command) also needs to be made to the ironic-inspector-image.

This also picks up the upstream fix to make searching for provisioning IP robust
https://github.com/metal3-io/ironic-inspector-image/commit/3a13a4e96e9c1f98b393a30c246eec6f48ba64c6
and uses the same script as ironic-image.

See https://github.com/openshift/ironic-image/pull/233.

### CODE REVIEW

**Review by elfosardo — APPROVED** [review]

**Review by awolffredhat — APPROVED** [review]
lgtm

**Comment by dtantsur** [comment]
/override ci/prow/prevalidation-e2e-metal-ipi-prevalidation 

Pre-validation tests are identical to regular tests, except when tagging new packages.

**Pull request merged**
